spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${configure.dev.address:localhost}:3306/dubbo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    addresses: ${configure.prod.address:127.0.0.1}
dubbo:
  application:
    name: Cabbage-Auth
    qos-port: 55555
  #    logger: slf4j
  protocol:
    name: dubbo
    port: 20883
  registry:
    address: zookeeper://${configure.prod.address:127.0.0.1}:2181

#写你自己安装zookeeper的服务器地址
server:
  port: 8080
  #configure:
  #  dev:
  #    address: xx
  #  prod:
  #    address: xx
configure:
  dev:
    address: xxx
  prod:
    address: xxx
  jwt:
    key: cabbage
    ttl: 1800000
    remember: 604800000
  verify_code:
    status: false


