server:
  port: 9999

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: @project.artifactId@
  cloud:
    nacos:

      discovery:
        server-addr: ${NACOS_HOST:cabbage-register}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - nacos:${spring.application.name}-@profiles.active@.yml