server:
  port: 8848
  servlet:
    context-path: /nacos
  error:
    include-message: ALWAYS

nacos:
  core:
    auth:
      plugin.nacos.token.secret.key: SecretKey012345678901234567890123456789012345678901234567890123456789
      enabled: false
      system.type: nacos
  security:
    ignore:
      urls: /,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**

spring:
  application:
    name: @artifactId@
  datasource:
    platform: mysql
  security:
    enabled: true
  boot: # 接入 spring boot admin
    admin:
      client:
        url: http://cabbage:1234
        username: cabbage
        password: cabbage

